export enum ModalType {
  NONE = 'NONE',
  WARNING = 'WARNING',
  CONFIRM = 'CONFIRM',
  LOADING = 'LOADING',
  SUCCESS = 'SUCCESS',
  ERROR = 'ERROR',
  REVIEW = 'REVIEW',
  SETTINGS = 'SETTINGS',
  SELECT_TOKEN = 'SELECT_TOKEN',
  SELECT_ACCOUNT = 'SELECT_ACCOUNT',
  SELECT_BRIDGE = 'SELECT_BRIDGE',
  // Add new modal types here...
}
